#!/bin/bash

if [ "$1" == "" ]; then
  echo "Usage: railsnew {app-name}"
  exit 1
fi

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

echo "================ Creating Application ================"
rails new $1 -T
cd $1

echo "================ Setting up Gemfile ================"
cat Gemfile | grep -v '^ *#' | grep -v '^$' > Gemfile.tmp
rm Gemfile
mv Gemfile.tmp Gemfile
cat "$DIR/Gemfile" >> Gemfile

bundle

echo "================ Replacing application.html.erb with haml ================"
cp -f "$DIR/application.html.haml" app/views/layouts/
rm app/views/layouts/application.html.erb

echo "================ Convert application.css to sass ================"
cp -f "$DIR/application.css.sass" app/assets/stylesheets/
rm app/assets/stylesheets/application.css

echo "================ Setting up RSpec ================"
rails g rspec:install

echo "================ Setting up SimpleForm ================"
rails g simple_form:install --bootstrap

echo "================ Set SASS as the default ================"
cd config/environments
head development.rb --lines=-1 > development.rb.tmp
echo "" >> development.rb.tmp
echo "  config.sass.preferred_syntax = :sass" >> development.rb.tmp
echo "end" >> development.rb.tmp
rm development.rb
mv development.rb.tmp development.rb
cd ../../

echo "================ Setting up Spork ================"
spork --bootstrap
cp -f "$DIR/spec_helper.rb" spec/
echo "--colour --rdb" > .rspec
cd config/environments
sed 's/config\.cache_classes = true/config.cache_classes = false/' test.rb > test.rb.tmp
rm test.rb
mv test.rb.tmp test.rb
cd ../../

echo "================ Setting up Capistrano ================"
capify .
sed "s/^ *# load 'deploy\/assets'/load 'deploy\/assets/" Capfile > Capfile.tmp
rm Capfile
mv Capfile.tmp Capfile
cp -f "$DIR/deploy.rb" config/deploy.rb


